"""Application layer for use-case orchestration."""

from flight_agent.application.requirement_commit import commit_requirement_transition
from flight_agent.application.requirement_interpretation import interpret_requirement
from flight_agent.application.requirement_normalization import (
    AirportCanonicalization,
    NormalizationContext,
    NormalizationIssue,
    NormalizationIssueCode,
    NormalizationResult,
    NormalizedRequirementCandidate,
    RequirementValidationIssue,
    RequirementValidationIssueCode,
    RequirementValidationResult,
    SearchReadinessStatus,
    normalize_initial_requirement,
    normalize_patch_requirement,
    validate_requirement,
)
from flight_agent.application.requirement_pipeline import (
    PostCommitProcessingStatus,
    RequirementPipelineOutcome,
    RequirementPipelineOutcomeStatus,
    execute_initial_requirement,
    execute_patch_requirement,
    execute_patch_requirement_from_current,
)
from flight_agent.application.requirement_transition import (
    PatchApplicationResult,
    PatchConstructionResult,
    PatchTransitionIssue,
    PatchTransitionIssueCode,
    PatchTransitionStatus,
    apply_patch_proposal,
    construct_patch_set,
)
from flight_agent.application.snapshot_assembly import (
    AssemblerVersion,
    CandidateSnapshotAssembler,
    FixtureSchemaVersion,
    SnapshotAssemblyInput,
    SnapshotAssemblyIssue,
    SnapshotAssemblyOutcome,
    SnapshotCreationStatus,
    SnapshotFreshnessEvidence,
    SnapshotProcessingManifest,
    build_processing_manifest,
)
from flight_agent.application.structured_entry import (
    SearchEligibleRequirement,
    StartStructuredRequirement,
    StructuredEntryResult,
    StructuredEntryStatus,
    StructuredRequirementCommand,
    structured_command_to_initial_proposal,
)

__all__ = [
    "AirportCanonicalization",
    "AssemblerVersion",
    "CandidateSnapshotAssembler",
    "FixtureSchemaVersion",
    "NormalizationContext",
    "NormalizationIssue",
    "NormalizationIssueCode",
    "NormalizationResult",
    "NormalizedRequirementCandidate",
    "PatchApplicationResult",
    "PatchConstructionResult",
    "PatchTransitionIssue",
    "PatchTransitionIssueCode",
    "PatchTransitionStatus",
    "PostCommitProcessingStatus",
    "RequirementPipelineOutcome",
    "RequirementPipelineOutcomeStatus",
    "RequirementValidationIssue",
    "RequirementValidationIssueCode",
    "RequirementValidationResult",
    "SearchEligibleRequirement",
    "SearchReadinessStatus",
    "SnapshotAssemblyInput",
    "SnapshotAssemblyIssue",
    "SnapshotAssemblyOutcome",
    "SnapshotCreationStatus",
    "SnapshotFreshnessEvidence",
    "SnapshotProcessingManifest",
    "StartStructuredRequirement",
    "StructuredEntryResult",
    "StructuredEntryStatus",
    "StructuredRequirementCommand",
    "apply_patch_proposal",
    "build_processing_manifest",
    "commit_requirement_transition",
    "construct_patch_set",
    "execute_initial_requirement",
    "execute_patch_requirement",
    "execute_patch_requirement_from_current",
    "interpret_requirement",
    "normalize_initial_requirement",
    "normalize_patch_requirement",
    "structured_command_to_initial_proposal",
    "validate_requirement",
]
