"""Abstract ports owned by the backend core boundary."""

from flight_agent.ports.flight_providers import (
    CoverageCompleteness,
    FlightProvider,
    ProviderAcquisitionId,
    ProviderCoverage,
    ProviderCoverageLimitation,
    ProviderDataStatus,
    ProviderExecutionStatus,
    ProviderId,
    ProviderSearchResult,
)
from flight_agent.ports.requirement_interpreter import (
    InitialInterpreterPayload,
    InitialRequirementProposal,
    InterpreterFailure,
    InterpreterInput,
    InterpreterMode,
    InterpreterPayload,
    InterpreterResult,
    InterpreterResultStatus,
    PatchInterpreterPayload,
    PatchProposalAction,
    PatchProposalOperation,
    PatchRequirementProposal,
    RequirementInterpretationContext,
    RequirementInterpreter,
    RequirementProposal,
)
from flight_agent.ports.requirement_repository import (
    CommitStatus,
    RequirementCommitResult,
    RequirementRepository,
)

__all__ = [
    "CommitStatus",
    "CoverageCompleteness",
    "FlightProvider",
    "InitialInterpreterPayload",
    "InitialRequirementProposal",
    "InterpreterFailure",
    "InterpreterInput",
    "InterpreterMode",
    "InterpreterPayload",
    "InterpreterResult",
    "InterpreterResultStatus",
    "PatchInterpreterPayload",
    "PatchProposalAction",
    "PatchProposalOperation",
    "PatchRequirementProposal",
    "ProviderAcquisitionId",
    "ProviderCoverage",
    "ProviderCoverageLimitation",
    "ProviderDataStatus",
    "ProviderExecutionStatus",
    "ProviderId",
    "ProviderSearchResult",
    "RequirementCommitResult",
    "RequirementInterpretationContext",
    "RequirementInterpreter",
    "RequirementProposal",
    "RequirementRepository",
]
